//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuddyBLL.UserProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDAL", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BuddyBLL.UserProfileService.UserProfile))]
    public partial class BaseDAL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
    [System.SerializableAttribute()]
    public partial class UserProfile : BuddyBLL.UserProfileService.BaseDAL {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enumclass.ViewType", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
    public enum EnumclassViewType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        standardView = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DetailedView = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enumclass.CircleType", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
    public enum EnumclassCircleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppLevelCircles = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCentrcsCircle = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterPageDetails", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
    [System.SerializableAttribute()]
    public partial class MasterPageDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlertCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TooltipTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] UserPhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlertCount {
            get {
                return this.AlertCountField;
            }
            set {
                if ((this.AlertCountField.Equals(value) != true)) {
                    this.AlertCountField = value;
                    this.RaisePropertyChanged("AlertCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TooltipText {
            get {
                return this.TooltipTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TooltipTextField, value) != true)) {
                    this.TooltipTextField = value;
                    this.RaisePropertyChanged("TooltipText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] UserPhoto {
            get {
                return this.UserPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhotoField, value) != true)) {
                    this.UserPhotoField = value;
                    this.RaisePropertyChanged("UserPhoto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enumclass.CircleCountRequired", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
    public enum EnumclassCircleCountRequired : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProfileService.IUserProfile")]
    public interface IUserProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetUserPhotograph", ReplyAction="http://tempuri.org/IUserProfile/GetUserPhotographResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetUserPhotographUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetUserPhotographExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet GetUserPhotograph(int AsscoiateId, string strGlobalAppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetAssociateDataByAssociateID", ReplyAction="http://tempuri.org/IUserProfile/GetAssociateDataByAssociateIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetAssociateDataByAssociateIDUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetAssociateDataByAssociateIDExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet GetAssociateDataByAssociateID(string strAssociateId, string GlobalAppID, BuddyBLL.UserProfileService.EnumclassViewType Display_View);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetAssociatesData", ReplyAction="http://tempuri.org/IUserProfile/GetAssociatesDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetAssociatesDataUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetAssociatesDataExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet GetAssociatesData(string strDepartmentId, string strDesignationID, string GlobalAppID, BuddyBLL.UserProfileService.EnumclassViewType Display_View);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetCircleDataByCircleId", ReplyAction="http://tempuri.org/IUserProfile/GetCircleDataByCircleIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetCircleDataByCircleIdExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetCircleDataByCircleIdUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        System.Data.DataSet GetCircleDataByCircleId(string circleID, string AssociateID, int iPageNo, int iPageSize, string GlobalAppID, BuddyBLL.UserProfileService.EnumclassViewType Display_View);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetCircleDatabyCircleName", ReplyAction="http://tempuri.org/IUserProfile/GetCircleDatabyCircleNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetCircleDatabyCircleNameUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetCircleDatabyCircleNameExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet GetCircleDatabyCircleName(string circleName, string GlobalAppId, string AssociateID, int iPageNo, int iPageSize, BuddyBLL.UserProfileService.EnumclassViewType Display_View);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetMultipleAssociatesPhotograph", ReplyAction="http://tempuri.org/IUserProfile/GetMultipleAssociatesPhotographResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetMultipleAssociatesPhotographUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetMultipleAssociatesPhotographExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet GetMultipleAssociatesPhotograph(string AssociateIDs, string strGlobalAppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/CreateAppLevelCircles", ReplyAction="http://tempuri.org/IUserProfile/CreateAppLevelCirclesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/CreateAppLevelCirclesExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/CreateAppLevelCirclesUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        string CreateAppLevelCircles(string strCircleName, string strGlobalAppID, string strCreatedByServiceID, string AssociateIDslist, string strCircleLogic, string strCircleDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/CreateUserCircles", ReplyAction="http://tempuri.org/IUserProfile/CreateUserCirclesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/CreateUserCirclesExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/CreateUserCirclesUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        string CreateUserCircles(string strCircleName, string strGlobalAppID, string strCreatedByAssociateID, string AssociateIDslist, string strCircleLogic, string strCircleDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/DeleteAssociatesFromCircle", ReplyAction="http://tempuri.org/IUserProfile/DeleteAssociatesFromCircleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/DeleteAssociatesFromCircleUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/DeleteAssociatesFromCircleExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        string DeleteAssociatesFromCircle(string strCircleName, string strGlobalAppID, string AssociateIDslist, string strCreatedUserID, BuddyBLL.UserProfileService.EnumclassCircleType strCircleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetAssociatesDetailsfromcircleIDS", ReplyAction="http://tempuri.org/IUserProfile/GetAssociatesDetailsfromcircleIDSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetAssociatesDetailsfromcircleIDSExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetAssociatesDetailsfromcircleIDSUserProfileFault" +
            "", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        System.Data.DataSet GetAssociatesDetailsfromcircleIDS(string strAssociate_ID, string strCircleIDs, byte bPagination_Required, int iPageNumber, int iPageSize, string GlobalAppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetOneCMasterDetails", ReplyAction="http://tempuri.org/IUserProfile/GetOneCMasterDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetOneCMasterDetailsExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetOneCMasterDetailsUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        BuddyBLL.UserProfileService.MasterPageDetails GetOneCMasterDetails(string strAssociate_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetCircleDetailsForAssociate", ReplyAction="http://tempuri.org/IUserProfile/GetCircleDetailsForAssociateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetCircleDetailsForAssociateUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetCircleDetailsForAssociateExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet GetCircleDetailsForAssociate(string strAssociate_ID, string GlobalAppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetCircleDetailsForCircleID", ReplyAction="http://tempuri.org/IUserProfile/GetCircleDetailsForCircleIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetCircleDetailsForCircleIDExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetCircleDetailsForCircleIDUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        System.Data.DataSet GetCircleDetailsForCircleID(int intCircleID, string strAssociateID, string strGlobalAppID, BuddyBLL.UserProfileService.EnumclassCircleCountRequired strCircleCountRequired);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/CircleDetailsSearch", ReplyAction="http://tempuri.org/IUserProfile/CircleDetailsSearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/CircleDetailsSearchUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/CircleDetailsSearchExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet CircleDetailsSearch(string strCircleName, string strCircleDescription, string strAssociateID, string strGlobalAppID, BuddyBLL.UserProfileService.EnumclassCircleCountRequired strCircleCountRequired);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetCircleIDDetailsForGlobalAPPID", ReplyAction="http://tempuri.org/IUserProfile/GetCircleIDDetailsForGlobalAPPIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetCircleIDDetailsForGlobalAPPIDExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetCircleIDDetailsForGlobalAPPIDUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        System.Data.DataSet GetCircleIDDetailsForGlobalAPPID(string strGlobalAppID, string strAssociateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPhotographBasedonUploadedtime", ReplyAction="http://tempuri.org/IUserProfile/GetPhotographBasedonUploadedtimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BuddyBLL.UserProfileService.UserProfile), Action="http://tempuri.org/IUserProfile/GetPhotographBasedonUploadedtimeUserProfileFault", Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CTS.OneC.ProfileService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IUserProfile/GetPhotographBasedonUploadedtimeExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Data.DataSet GetPhotographBasedonUploadedtime(System.DateTime dtUploadDate, string strGlobalAppID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileChannel : BuddyBLL.UserProfileService.IUserProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileClient : System.ServiceModel.ClientBase<BuddyBLL.UserProfileService.IUserProfile>, BuddyBLL.UserProfileService.IUserProfile {
        
        public UserProfileClient() {
        }
        
        public UserProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetUserPhotograph(int AsscoiateId, string strGlobalAppID) {
            return base.Channel.GetUserPhotograph(AsscoiateId, strGlobalAppID);
        }
        
        public System.Data.DataSet GetAssociateDataByAssociateID(string strAssociateId, string GlobalAppID, BuddyBLL.UserProfileService.EnumclassViewType Display_View) {
            return base.Channel.GetAssociateDataByAssociateID(strAssociateId, GlobalAppID, Display_View);
        }
        
        public System.Data.DataSet GetAssociatesData(string strDepartmentId, string strDesignationID, string GlobalAppID, BuddyBLL.UserProfileService.EnumclassViewType Display_View) {
            return base.Channel.GetAssociatesData(strDepartmentId, strDesignationID, GlobalAppID, Display_View);
        }
        
        public System.Data.DataSet GetCircleDataByCircleId(string circleID, string AssociateID, int iPageNo, int iPageSize, string GlobalAppID, BuddyBLL.UserProfileService.EnumclassViewType Display_View) {
            return base.Channel.GetCircleDataByCircleId(circleID, AssociateID, iPageNo, iPageSize, GlobalAppID, Display_View);
        }
        
        public System.Data.DataSet GetCircleDatabyCircleName(string circleName, string GlobalAppId, string AssociateID, int iPageNo, int iPageSize, BuddyBLL.UserProfileService.EnumclassViewType Display_View) {
            return base.Channel.GetCircleDatabyCircleName(circleName, GlobalAppId, AssociateID, iPageNo, iPageSize, Display_View);
        }
        
        public System.Data.DataSet GetMultipleAssociatesPhotograph(string AssociateIDs, string strGlobalAppID) {
            return base.Channel.GetMultipleAssociatesPhotograph(AssociateIDs, strGlobalAppID);
        }
        
        public string CreateAppLevelCircles(string strCircleName, string strGlobalAppID, string strCreatedByServiceID, string AssociateIDslist, string strCircleLogic, string strCircleDescription) {
            return base.Channel.CreateAppLevelCircles(strCircleName, strGlobalAppID, strCreatedByServiceID, AssociateIDslist, strCircleLogic, strCircleDescription);
        }
        
        public string CreateUserCircles(string strCircleName, string strGlobalAppID, string strCreatedByAssociateID, string AssociateIDslist, string strCircleLogic, string strCircleDescription) {
            return base.Channel.CreateUserCircles(strCircleName, strGlobalAppID, strCreatedByAssociateID, AssociateIDslist, strCircleLogic, strCircleDescription);
        }
        
        public string DeleteAssociatesFromCircle(string strCircleName, string strGlobalAppID, string AssociateIDslist, string strCreatedUserID, BuddyBLL.UserProfileService.EnumclassCircleType strCircleType) {
            return base.Channel.DeleteAssociatesFromCircle(strCircleName, strGlobalAppID, AssociateIDslist, strCreatedUserID, strCircleType);
        }
        
        public System.Data.DataSet GetAssociatesDetailsfromcircleIDS(string strAssociate_ID, string strCircleIDs, byte bPagination_Required, int iPageNumber, int iPageSize, string GlobalAppID) {
            return base.Channel.GetAssociatesDetailsfromcircleIDS(strAssociate_ID, strCircleIDs, bPagination_Required, iPageNumber, iPageSize, GlobalAppID);
        }
        
        public BuddyBLL.UserProfileService.MasterPageDetails GetOneCMasterDetails(string strAssociate_ID) {
            return base.Channel.GetOneCMasterDetails(strAssociate_ID);
        }
        
        public System.Data.DataSet GetCircleDetailsForAssociate(string strAssociate_ID, string GlobalAppId) {
            return base.Channel.GetCircleDetailsForAssociate(strAssociate_ID, GlobalAppId);
        }
        
        public System.Data.DataSet GetCircleDetailsForCircleID(int intCircleID, string strAssociateID, string strGlobalAppID, BuddyBLL.UserProfileService.EnumclassCircleCountRequired strCircleCountRequired) {
            return base.Channel.GetCircleDetailsForCircleID(intCircleID, strAssociateID, strGlobalAppID, strCircleCountRequired);
        }
        
        public System.Data.DataSet CircleDetailsSearch(string strCircleName, string strCircleDescription, string strAssociateID, string strGlobalAppID, BuddyBLL.UserProfileService.EnumclassCircleCountRequired strCircleCountRequired) {
            return base.Channel.CircleDetailsSearch(strCircleName, strCircleDescription, strAssociateID, strGlobalAppID, strCircleCountRequired);
        }
        
        public System.Data.DataSet GetCircleIDDetailsForGlobalAPPID(string strGlobalAppID, string strAssociateID) {
            return base.Channel.GetCircleIDDetailsForGlobalAPPID(strGlobalAppID, strAssociateID);
        }
        
        public System.Data.DataSet GetPhotographBasedonUploadedtime(System.DateTime dtUploadDate, string strGlobalAppID) {
            return base.Channel.GetPhotographBasedonUploadedtime(dtUploadDate, strGlobalAppID);
        }
    }
}
