//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneC.OnBoarding.WebApp.FileUploadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppTemplateCollection", Namespace="http://schemas.datacontract.org/2004/07/OneC_GenericUploadDataContract")]
    [System.SerializableAttribute()]
    public partial class AppTemplateCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OneC.OnBoarding.WebApp.FileUploadService.AppTemplate[] AppTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable DtAppTemplateCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OneC.OnBoarding.WebApp.FileUploadService.AppTemplate[] AppTemplate {
            get {
                return this.AppTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.AppTemplateField, value) != true)) {
                    this.AppTemplateField = value;
                    this.RaisePropertyChanged("AppTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable DtAppTemplateCollection {
            get {
                return this.DtAppTemplateCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DtAppTemplateCollectionField, value) != true)) {
                    this.DtAppTemplateCollectionField = value;
                    this.RaisePropertyChanged("DtAppTemplateCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedBy {
            get {
                return this.RequestedByField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedByField, value) != true)) {
                    this.RequestedByField = value;
                    this.RaisePropertyChanged("RequestedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppTemplate", Namespace="http://schemas.datacontract.org/2004/07/OneC_GenericUploadDataContract")]
    [System.SerializableAttribute()]
    public partial class AppTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppTemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxFileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidFileTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppTemplateId {
            get {
                return this.AppTemplateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppTemplateIdField, value) != true)) {
                    this.AppTemplateIdField = value;
                    this.RaisePropertyChanged("AppTemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxFileSize {
            get {
                return this.MaxFileSizeField;
            }
            set {
                if ((this.MaxFileSizeField.Equals(value) != true)) {
                    this.MaxFileSizeField = value;
                    this.RaisePropertyChanged("MaxFileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateDescription {
            get {
                return this.TemplateDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateDescriptionField, value) != true)) {
                    this.TemplateDescriptionField = value;
                    this.RaisePropertyChanged("TemplateDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidFileTypes {
            get {
                return this.ValidFileTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidFileTypesField, value) != true)) {
                    this.ValidFileTypesField = value;
                    this.RaisePropertyChanged("ValidFileTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileUploadDC", Namespace="http://schemas.datacontract.org/2004/07/OneC_GenericUploadDataContract")]
    [System.SerializableAttribute()]
    public partial class FileUploadDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppTemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FileContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileSaveNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileScanStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileUploadIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppTemplateId {
            get {
                return this.AppTemplateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppTemplateIdField, value) != true)) {
                    this.AppTemplateIdField = value;
                    this.RaisePropertyChanged("AppTemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> FileContentId {
            get {
                return this.FileContentIdField;
            }
            set {
                if ((this.FileContentIdField.Equals(value) != true)) {
                    this.FileContentIdField = value;
                    this.RaisePropertyChanged("FileContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileLocation {
            get {
                return this.FileLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.FileLocationField, value) != true)) {
                    this.FileLocationField = value;
                    this.RaisePropertyChanged("FileLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSaveName {
            get {
                return this.FileSaveNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileSaveNameField, value) != true)) {
                    this.FileSaveNameField = value;
                    this.RaisePropertyChanged("FileSaveName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileScanStatus {
            get {
                return this.FileScanStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FileScanStatusField, value) != true)) {
                    this.FileScanStatusField = value;
                    this.RaisePropertyChanged("FileScanStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileURL {
            get {
                return this.FileURLField;
            }
            set {
                if ((object.ReferenceEquals(this.FileURLField, value) != true)) {
                    this.FileURLField = value;
                    this.RaisePropertyChanged("FileURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileUploadId {
            get {
                return this.FileUploadIdField;
            }
            set {
                if ((this.FileUploadIdField.Equals(value) != true)) {
                    this.FileUploadIdField = value;
                    this.RaisePropertyChanged("FileUploadId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileUploadCollection", Namespace="http://schemas.datacontract.org/2004/07/OneC_GenericUploadDataContract")]
    [System.SerializableAttribute()]
    public partial class FileUploadCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable DtBulkUpdateScanStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC[] FileUploadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable DtBulkUpdateScanStatus {
            get {
                return this.DtBulkUpdateScanStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DtBulkUpdateScanStatusField, value) != true)) {
                    this.DtBulkUpdateScanStatusField = value;
                    this.RaisePropertyChanged("DtBulkUpdateScanStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC[] FileUpload {
            get {
                return this.FileUploadField;
            }
            set {
                if ((object.ReferenceEquals(this.FileUploadField, value) != true)) {
                    this.FileUploadField = value;
                    this.RaisePropertyChanged("FileUpload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedBy {
            get {
                return this.RequestedByField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedByField, value) != true)) {
                    this.RequestedByField = value;
                    this.RaisePropertyChanged("RequestedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MFileuploadResponse", Namespace="http://schemas.datacontract.org/2004/07/OneC_GenericUploadMessageContract")]
    [System.SerializableAttribute()]
    public partial class MFileuploadResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncryptedFileUploadIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FileContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExternalURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileUploadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilestatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] OutgoingFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptedFileUploadID {
            get {
                return this.EncryptedFileUploadIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedFileUploadIDField, value) != true)) {
                    this.EncryptedFileUploadIDField = value;
                    this.RaisePropertyChanged("EncryptedFileUploadID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> FileContentId {
            get {
                return this.FileContentIdField;
            }
            set {
                if ((this.FileContentIdField.Equals(value) != true)) {
                    this.FileContentIdField = value;
                    this.RaisePropertyChanged("FileContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileException {
            get {
                return this.FileExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExceptionField, value) != true)) {
                    this.FileExceptionField = value;
                    this.RaisePropertyChanged("FileException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExternalURL {
            get {
                return this.FileExternalURLField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExternalURLField, value) != true)) {
                    this.FileExternalURLField = value;
                    this.RaisePropertyChanged("FileExternalURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileLocation {
            get {
                return this.FileLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.FileLocationField, value) != true)) {
                    this.FileLocationField = value;
                    this.RaisePropertyChanged("FileLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileURL {
            get {
                return this.FileURLField;
            }
            set {
                if ((object.ReferenceEquals(this.FileURLField, value) != true)) {
                    this.FileURLField = value;
                    this.RaisePropertyChanged("FileURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileUploadId {
            get {
                return this.FileUploadIdField;
            }
            set {
                if ((this.FileUploadIdField.Equals(value) != true)) {
                    this.FileUploadIdField = value;
                    this.RaisePropertyChanged("FileUploadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filestatus {
            get {
                return this.FilestatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FilestatusField, value) != true)) {
                    this.FilestatusField = value;
                    this.RaisePropertyChanged("Filestatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] OutgoingFile {
            get {
                return this.OutgoingFileField;
            }
            set {
                if ((object.ReferenceEquals(this.OutgoingFileField, value) != true)) {
                    this.OutgoingFileField = value;
                    this.RaisePropertyChanged("OutgoingFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileUploadDetailsRequest", Namespace="http://schemas.datacontract.org/2004/07/OneC_GenericUploadMessageContract")]
    [System.SerializableAttribute()]
    public partial class FileUploadDetailsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppTemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssociateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncryptedFileUploadIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FileContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileSaveNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileUploadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IncomingFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppTemplateId {
            get {
                return this.AppTemplateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppTemplateIdField, value) != true)) {
                    this.AppTemplateIdField = value;
                    this.RaisePropertyChanged("AppTemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssociateId {
            get {
                return this.AssociateIdField;
            }
            set {
                if ((this.AssociateIdField.Equals(value) != true)) {
                    this.AssociateIdField = value;
                    this.RaisePropertyChanged("AssociateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptedFileUploadID {
            get {
                return this.EncryptedFileUploadIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedFileUploadIDField, value) != true)) {
                    this.EncryptedFileUploadIDField = value;
                    this.RaisePropertyChanged("EncryptedFileUploadID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> FileContentId {
            get {
                return this.FileContentIdField;
            }
            set {
                if ((this.FileContentIdField.Equals(value) != true)) {
                    this.FileContentIdField = value;
                    this.RaisePropertyChanged("FileContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSaveName {
            get {
                return this.FileSaveNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileSaveNameField, value) != true)) {
                    this.FileSaveNameField = value;
                    this.RaisePropertyChanged("FileSaveName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileUploadId {
            get {
                return this.FileUploadIdField;
            }
            set {
                if ((this.FileUploadIdField.Equals(value) != true)) {
                    this.FileUploadIdField = value;
                    this.RaisePropertyChanged("FileUploadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] IncomingFile {
            get {
                return this.IncomingFileField;
            }
            set {
                if ((object.ReferenceEquals(this.IncomingFileField, value) != true)) {
                    this.IncomingFileField = value;
                    this.RaisePropertyChanged("IncomingFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileUploadService.IDocumentUploadService")]
    public interface IDocumentUploadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/GetTemplate", ReplyAction="http://tempuri.org/IDocumentUploadService/GetTemplateResponse")]
        void GetTemplate(ref OneC.OnBoarding.WebApp.FileUploadService.AppTemplateCollection objAppTemplateCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/GetFileURL", ReplyAction="http://tempuri.org/IDocumentUploadService/GetFileURLResponse")]
        OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC GetFileURL(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC objFileUploadDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/GetFilesForScanAndUpdateFileStatus", ReplyAction="http://tempuri.org/IDocumentUploadService/GetFilesForScanAndUpdateFileStatusRespo" +
            "nse")]
        OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse GetFilesForScanAndUpdateFileStatus(OneC.OnBoarding.WebApp.FileUploadService.FileUploadCollection objFileUploadCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/DeleteFileUploadDetails", ReplyAction="http://tempuri.org/IDocumentUploadService/DeleteFileUploadDetailsResponse")]
        OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DeleteFileUploadDetails(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDetailsRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/DeleteFileUpload", ReplyAction="http://tempuri.org/IDocumentUploadService/DeleteFileUploadResponse")]
        OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DeleteFileUpload(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDetailsRequest objFileUploadDetailsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/DownloadFile", ReplyAction="http://tempuri.org/IDocumentUploadService/DownloadFileResponse")]
        OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DownloadFile(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC objFileUploadDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/UploadFile_WithResponse", ReplyAction="http://tempuri.org/IDocumentUploadService/UploadFile_WithResponseResponse")]
        OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse UploadFile_WithResponse(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDetailsRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentUploadService/DownloadFile_WithDecryption", ReplyAction="http://tempuri.org/IDocumentUploadService/DownloadFile_WithDecryptionResponse")]
        OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DownloadFile_WithDecryption(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC objFileUploadDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentUploadServiceChannel : OneC.OnBoarding.WebApp.FileUploadService.IDocumentUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentUploadServiceClient : System.ServiceModel.ClientBase<OneC.OnBoarding.WebApp.FileUploadService.IDocumentUploadService>, OneC.OnBoarding.WebApp.FileUploadService.IDocumentUploadService {
        
        public DocumentUploadServiceClient() {
        }
        
        public DocumentUploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentUploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentUploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentUploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetTemplate(ref OneC.OnBoarding.WebApp.FileUploadService.AppTemplateCollection objAppTemplateCollection) {
            base.Channel.GetTemplate(ref objAppTemplateCollection);
        }
        
        public OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC GetFileURL(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC objFileUploadDC) {
            return base.Channel.GetFileURL(objFileUploadDC);
        }
        
        public OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse GetFilesForScanAndUpdateFileStatus(OneC.OnBoarding.WebApp.FileUploadService.FileUploadCollection objFileUploadCollection) {
            return base.Channel.GetFilesForScanAndUpdateFileStatus(objFileUploadCollection);
        }
        
        public OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DeleteFileUploadDetails(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDetailsRequest req) {
            return base.Channel.DeleteFileUploadDetails(req);
        }
        
        public OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DeleteFileUpload(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDetailsRequest objFileUploadDetailsRequest) {
            return base.Channel.DeleteFileUpload(objFileUploadDetailsRequest);
        }
        
        public OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DownloadFile(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC objFileUploadDC) {
            return base.Channel.DownloadFile(objFileUploadDC);
        }
        
        public OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse UploadFile_WithResponse(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDetailsRequest req) {
            return base.Channel.UploadFile_WithResponse(req);
        }
        
        public OneC.OnBoarding.WebApp.FileUploadService.MFileuploadResponse DownloadFile_WithDecryption(OneC.OnBoarding.WebApp.FileUploadService.FileUploadDC objFileUploadDC) {
            return base.Channel.DownloadFile_WithDecryption(objFileUploadDC);
        }
    }
}
