//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneC.OnBoarding.WebApp.Service.OBUtilityMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
        "acts/", ConfigurationName="Service.OBUtilityMethods.IOBUtilityMethods")]
    public interface IOBUtilityMethods {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveSANUploadDetails", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveSANUploadDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveSANUploadDetailsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        void SaveSANUploadDetails(OneC.OnBoarding.DC.UtilityDC.SANUploadDetails fileUpload);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/LogException", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/LogExceptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/LogExceptionOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        void LogException(OneC.OnBoarding.DC.UtilityDC.ErrorDetails errDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SetSession", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SetSessionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SetSessionOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.SessionDetails SetSession(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/LogEventData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/LogEventDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/LogEventDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        void LogEventData(OneC.OnBoarding.DC.UtilityDC.EventLog evntLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchRoles", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchRolesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchRolesOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.UserRolesContainer FetchRoles(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetSystemKey", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetSystemKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetSystemKeyOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.SystemKey GetSystemKey(OneC.OnBoarding.DC.UtilityDC.SystemKey sysKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/IsPageAllowed", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/IsPageAllowedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/IsPageAllowedOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.PageAccess IsPageAllowed(OneC.OnBoarding.DC.UtilityDC.PageAccess pageAccess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/IsSessionActive", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/IsSessionActiveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/IsSessionActiveOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        bool IsSessionActive(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetMessage", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetMessageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetMessageOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.Messages GetMessage(OneC.OnBoarding.DC.UtilityDC.Messages messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetExternalUserInfo", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetExternalUserInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetExternalUserInfoOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.UserInfoDC GetExternalUserInfo(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendNotificationMail", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendNotificationMailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendNotificationMailOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SendNotificationMail(OneC.OnBoarding.DC.UtilityDC.MailData objMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendMail", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendMailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendMailOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string SendMail(OneC.OnBoarding.DC.UtilityDC.MailData maildata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendMailWithConfirmBoolStatus", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendMailWithConfirmBoolStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SendMailWithConfirmBoolStatusOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        bool SendMailWithConfirmBoolStatus(OneC.OnBoarding.DC.UtilityDC.MailData maildata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UploadAttachment", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UploadAttachmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UploadAttachmentOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UploadAttachment(OneC.OnBoarding.DC.UtilityDC.MailAttachment objAttachments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetMckinleyCategories", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetMckinleyCategoriesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetMckinleyCategoriesOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.MCkinleyDC GetMckinleyCategories(OneC.OnBoarding.DC.UtilityDC.MCkinleyDC mckinleyCategories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetFilterDate", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetFilterDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetFilterDateOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.SystemKey GetFilterDate(OneC.OnBoarding.DC.UtilityDC.SystemKey sysKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetSurveyData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetSurveyDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetSurveyDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.SurveyDC GetSurveyData(OneC.OnBoarding.DC.UtilityDC.SurveyDC surveyData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateECMFileUploadStatus", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateECMFileUploadStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateECMFileUploadStatusOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UpdateECMFileUploadStatus(OneC.OnBoarding.DC.UtilityDC.VirtualDocumentDetail objDocumentDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateIDMRegistartionforRetry", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateIDMRegistartionforRetryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateIDMRegistartionforRetryOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UpdateIDMRegistartionforRetry(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetEventMailContent", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetEventMailContentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetEventMailContentOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.GetMailContent GetEventMailContent(OneC.OnBoarding.DC.UtilityDC.GetMailContent getMailContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveUploadedDocName", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveUploadedDocNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveUploadedDocNameOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SaveUploadedDocName(OneC.OnBoarding.DC.UtilityDC.ECMDocument objDocName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetPageMenuMappings", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetPageMenuMappingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetPageMenuMappingsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.PageMenuMappingContainer GetPageMenuMappings(OneC.OnBoarding.DC.UtilityDC.PageMenuMappingContract objPageMenuMappingContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchUserAssignRoles", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchUserAssignRolesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchUserAssignRolesOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.UserRolesAccessContainer FetchUserAssignRoles(OneC.OnBoarding.DC.UtilityDC.RoleAccessDC objRoleAccessDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchActiveUsers", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchActiveUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/FetchActiveUsersOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.UserRolesAccessContainer FetchActiveUsers(OneC.OnBoarding.DC.UtilityDC.RoleAccessDC objRoleAccessDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SetRoleToAssociate", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SetRoleToAssociateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SetRoleToAssociateOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SetRoleToAssociate(OneC.OnBoarding.DC.UtilityDC.RoleAccessDC objRoleAccessDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateCandidateStateAndLocationDetails", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateCandidateStateAndLocationDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/UpdateCandidateStateAndLocationDetailsOBFaultContractFCFa" +
            "ult", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UpdateCandidateStateAndLocationDetails(OneC.OnBoarding.DC.UtilityDC.StartDateAndLocationDC candDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetUploadList", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetUploadListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetUploadListOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetUploadList(OneC.OnBoarding.DC.UtilityDC.UploadUtiltiyDC fileUpload);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveUploadResponse", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveUploadResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/SaveUploadResponseOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string SaveUploadResponse(OneC.OnBoarding.DC.UtilityDC.UploadUtiltiyDC fileUpload);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetECMUploadURL", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetECMUploadURLResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/OBUtilityMethods/ServiceContr" +
            "acts/IOBUtilityMethods/GetECMUploadURLOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetECMUploadURL(OneC.OnBoarding.DC.UtilityDC.UploadUtiltiyDC fileUpload);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOBUtilityMethodsChannel : OneC.OnBoarding.WebApp.Service.OBUtilityMethods.IOBUtilityMethods, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OBUtilityMethodsClient : System.ServiceModel.ClientBase<OneC.OnBoarding.WebApp.Service.OBUtilityMethods.IOBUtilityMethods>, OneC.OnBoarding.WebApp.Service.OBUtilityMethods.IOBUtilityMethods {
        
        public OBUtilityMethodsClient() {
        }
        
        public OBUtilityMethodsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OBUtilityMethodsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OBUtilityMethodsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OBUtilityMethodsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveSANUploadDetails(OneC.OnBoarding.DC.UtilityDC.SANUploadDetails fileUpload) {
            base.Channel.SaveSANUploadDetails(fileUpload);
        }
        
        public void LogException(OneC.OnBoarding.DC.UtilityDC.ErrorDetails errDetail) {
            base.Channel.LogException(errDetail);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.SessionDetails SetSession(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail) {
            return base.Channel.SetSession(sessionDetail);
        }
        
        public void LogEventData(OneC.OnBoarding.DC.UtilityDC.EventLog evntLog) {
            base.Channel.LogEventData(evntLog);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.UserRolesContainer FetchRoles(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail) {
            return base.Channel.FetchRoles(sessionDetail);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.SystemKey GetSystemKey(OneC.OnBoarding.DC.UtilityDC.SystemKey sysKey) {
            return base.Channel.GetSystemKey(sysKey);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.PageAccess IsPageAllowed(OneC.OnBoarding.DC.UtilityDC.PageAccess pageAccess) {
            return base.Channel.IsPageAllowed(pageAccess);
        }
        
        public bool IsSessionActive(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail) {
            return base.Channel.IsSessionActive(sessionDetail);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.Messages GetMessage(OneC.OnBoarding.DC.UtilityDC.Messages messages) {
            return base.Channel.GetMessage(messages);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.UserInfoDC GetExternalUserInfo(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail) {
            return base.Channel.GetExternalUserInfo(sessionDetail);
        }
        
        public int SendNotificationMail(OneC.OnBoarding.DC.UtilityDC.MailData objMail) {
            return base.Channel.SendNotificationMail(objMail);
        }
        
        public string SendMail(OneC.OnBoarding.DC.UtilityDC.MailData maildata) {
            return base.Channel.SendMail(maildata);
        }
        
        public bool SendMailWithConfirmBoolStatus(OneC.OnBoarding.DC.UtilityDC.MailData maildata) {
            return base.Channel.SendMailWithConfirmBoolStatus(maildata);
        }
        
        public int UploadAttachment(OneC.OnBoarding.DC.UtilityDC.MailAttachment objAttachments) {
            return base.Channel.UploadAttachment(objAttachments);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.MCkinleyDC GetMckinleyCategories(OneC.OnBoarding.DC.UtilityDC.MCkinleyDC mckinleyCategories) {
            return base.Channel.GetMckinleyCategories(mckinleyCategories);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.SystemKey GetFilterDate(OneC.OnBoarding.DC.UtilityDC.SystemKey sysKey) {
            return base.Channel.GetFilterDate(sysKey);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.SurveyDC GetSurveyData(OneC.OnBoarding.DC.UtilityDC.SurveyDC surveyData) {
            return base.Channel.GetSurveyData(surveyData);
        }
        
        public int UpdateECMFileUploadStatus(OneC.OnBoarding.DC.UtilityDC.VirtualDocumentDetail objDocumentDetail) {
            return base.Channel.UpdateECMFileUploadStatus(objDocumentDetail);
        }
        
        public int UpdateIDMRegistartionforRetry(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail) {
            return base.Channel.UpdateIDMRegistartionforRetry(sessionDetail);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.GetMailContent GetEventMailContent(OneC.OnBoarding.DC.UtilityDC.GetMailContent getMailContent) {
            return base.Channel.GetEventMailContent(getMailContent);
        }
        
        public int SaveUploadedDocName(OneC.OnBoarding.DC.UtilityDC.ECMDocument objDocName) {
            return base.Channel.SaveUploadedDocName(objDocName);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.PageMenuMappingContainer GetPageMenuMappings(OneC.OnBoarding.DC.UtilityDC.PageMenuMappingContract objPageMenuMappingContract) {
            return base.Channel.GetPageMenuMappings(objPageMenuMappingContract);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.UserRolesAccessContainer FetchUserAssignRoles(OneC.OnBoarding.DC.UtilityDC.RoleAccessDC objRoleAccessDC) {
            return base.Channel.FetchUserAssignRoles(objRoleAccessDC);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.UserRolesAccessContainer FetchActiveUsers(OneC.OnBoarding.DC.UtilityDC.RoleAccessDC objRoleAccessDC) {
            return base.Channel.FetchActiveUsers(objRoleAccessDC);
        }
        
        public int SetRoleToAssociate(OneC.OnBoarding.DC.UtilityDC.RoleAccessDC objRoleAccessDC) {
            return base.Channel.SetRoleToAssociate(objRoleAccessDC);
        }
        
        public int UpdateCandidateStateAndLocationDetails(OneC.OnBoarding.DC.UtilityDC.StartDateAndLocationDC candDetail) {
            return base.Channel.UpdateCandidateStateAndLocationDetails(candDetail);
        }
        
        public string GetUploadList(OneC.OnBoarding.DC.UtilityDC.UploadUtiltiyDC fileUpload) {
            return base.Channel.GetUploadList(fileUpload);
        }
        
        public string SaveUploadResponse(OneC.OnBoarding.DC.UtilityDC.UploadUtiltiyDC fileUpload) {
            return base.Channel.SaveUploadResponse(fileUpload);
        }
        
        public string GetECMUploadURL(OneC.OnBoarding.DC.UtilityDC.UploadUtiltiyDC fileUpload) {
            return base.Channel.GetECMUploadURL(fileUpload);
        }
    }
}
