//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneC.OnBoarding.WebApp.Service.BGVUtilityMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
        "racts/", ConfigurationName="Service.BGVUtilityMethods.IBGVUtilityMethods")]
    public interface IBGVUtilityMethods {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/FetchVendorDashboardData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/FetchVendorDashboardDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/FetchVendorDashboardDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string FetchVendorDashboardData(OneC.OnBoarding.DC.BGVDC.VendorDashboardParams objVendorDashboardParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetVendorCandidateData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetVendorCandidateDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetVendorCandidateDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetVendorCandidateData(OneC.OnBoarding.DC.BGVDC.VendorCandidateInfo objVendorCandidateInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetVendorDocListInfo", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetVendorDocListInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetVendorDocListInfoOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetVendorDocListInfo(OneC.OnBoarding.DC.BGVDC.VendorDashboardParams objVendorDashboardParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveVendorDocListInfo", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveVendorDocListInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveVendorDocListInfoOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string SaveVendorDocListInfo(OneC.OnBoarding.DC.BGVDC.VendorDocListInfoParams objVendorDocListInfoParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetAssignVendorCandidateData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetAssignVendorCandidateDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetAssignVendorCandidateDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetAssignVendorCandidateData(OneC.OnBoarding.DC.BGVDC.CandidateBGVData objAssignVendorData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetAssignVendorComponents", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetAssignVendorComponentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetAssignVendorComponentsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetAssignVendorComponents(OneC.OnBoarding.DC.BGVDC.CandidateBGVData objAssignVendorData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveAssignVendorCandidateData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveAssignVendorCandidateDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveAssignVendorCandidateDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string SaveAssignVendorCandidateData(OneC.OnBoarding.DC.BGVDC.CandidateBGVData objAssignVendorData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/BackPapers", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/BackPapersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/BackPapersOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string BackPapers(OneC.OnBoarding.DC.BGVDC.BackPapersParams objBackPapersParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/DocListInfo", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/DocListInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/DocListInfoOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string DocListInfo(OneC.OnBoarding.DC.BGVDC.DocListInfo objDocListInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ComponentData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ComponentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ComponentDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string ComponentData(OneC.OnBoarding.DC.BGVDC.ComponentData objComponentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveComponentData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveComponentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveComponentDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SaveComponentData(OneC.OnBoarding.DC.BGVDC.SaveComponent objSaveComponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveVerificationData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveVerificationDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SaveVerificationDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SaveVerificationData(OneC.OnBoarding.DC.BGVDC.SaveComponent objSaveComponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/AutoSearch", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/AutoSearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/AutoSearchOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.BGVDC.Autocomplete AutoSearch(OneC.OnBoarding.DC.BGVDC.Autocomplete objAutocomplete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ValidateComponentData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ValidateComponentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ValidateComponentDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.BGVDC.Validation ValidateComponentData(OneC.OnBoarding.DC.BGVDC.Validation objValidation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/PersonalData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/PersonalDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/PersonalDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string PersonalData(OneC.OnBoarding.DC.BGVDC.CandidateInformationDC objCandidateInformationDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SavePersonalData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SavePersonalDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/SavePersonalDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SavePersonalData(OneC.OnBoarding.DC.BGVDC.CandidateInformationDC objCandidateInformationDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ValidatePersonalInfo", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ValidatePersonalInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/ValidatePersonalInfoOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.BGVDC.ValidatePersonalData ValidatePersonalInfo(OneC.OnBoarding.DC.BGVDC.ValidatePersonalData objValidation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPagePathForRole", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPagePathForRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPagePathForRoleOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetPagePathForRole(OneC.OnBoarding.DC.BGVDC.PageNavigationDC objPageNavigationDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPageNotifications", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPageNotificationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPageNotificationsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string[] GetPageNotifications(OneC.OnBoarding.DC.BGVDC.PageNotifications objPageNotifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPageComparisionData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPageComparisionDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/BGVUtilityMethods/ServiceCont" +
            "racts/IBGVUtilityMethods/GetPageComparisionDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetPageComparisionData(OneC.OnBoarding.DC.BGVDC.CompareDC objCompareDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBGVUtilityMethodsChannel : OneC.OnBoarding.WebApp.Service.BGVUtilityMethods.IBGVUtilityMethods, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BGVUtilityMethodsClient : System.ServiceModel.ClientBase<OneC.OnBoarding.WebApp.Service.BGVUtilityMethods.IBGVUtilityMethods>, OneC.OnBoarding.WebApp.Service.BGVUtilityMethods.IBGVUtilityMethods {
        
        public BGVUtilityMethodsClient() {
        }
        
        public BGVUtilityMethodsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BGVUtilityMethodsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BGVUtilityMethodsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BGVUtilityMethodsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FetchVendorDashboardData(OneC.OnBoarding.DC.BGVDC.VendorDashboardParams objVendorDashboardParams) {
            return base.Channel.FetchVendorDashboardData(objVendorDashboardParams);
        }
        
        public string GetVendorCandidateData(OneC.OnBoarding.DC.BGVDC.VendorCandidateInfo objVendorCandidateInfo) {
            return base.Channel.GetVendorCandidateData(objVendorCandidateInfo);
        }
        
        public string GetVendorDocListInfo(OneC.OnBoarding.DC.BGVDC.VendorDashboardParams objVendorDashboardParams) {
            return base.Channel.GetVendorDocListInfo(objVendorDashboardParams);
        }
        
        public string SaveVendorDocListInfo(OneC.OnBoarding.DC.BGVDC.VendorDocListInfoParams objVendorDocListInfoParams) {
            return base.Channel.SaveVendorDocListInfo(objVendorDocListInfoParams);
        }
        
        public string GetAssignVendorCandidateData(OneC.OnBoarding.DC.BGVDC.CandidateBGVData objAssignVendorData) {
            return base.Channel.GetAssignVendorCandidateData(objAssignVendorData);
        }
        
        public string GetAssignVendorComponents(OneC.OnBoarding.DC.BGVDC.CandidateBGVData objAssignVendorData) {
            return base.Channel.GetAssignVendorComponents(objAssignVendorData);
        }
        
        public string SaveAssignVendorCandidateData(OneC.OnBoarding.DC.BGVDC.CandidateBGVData objAssignVendorData) {
            return base.Channel.SaveAssignVendorCandidateData(objAssignVendorData);
        }
        
        public string BackPapers(OneC.OnBoarding.DC.BGVDC.BackPapersParams objBackPapersParams) {
            return base.Channel.BackPapers(objBackPapersParams);
        }
        
        public string DocListInfo(OneC.OnBoarding.DC.BGVDC.DocListInfo objDocListInfo) {
            return base.Channel.DocListInfo(objDocListInfo);
        }
        
        public string ComponentData(OneC.OnBoarding.DC.BGVDC.ComponentData objComponentData) {
            return base.Channel.ComponentData(objComponentData);
        }
        
        public int SaveComponentData(OneC.OnBoarding.DC.BGVDC.SaveComponent objSaveComponent) {
            return base.Channel.SaveComponentData(objSaveComponent);
        }
        
        public int SaveVerificationData(OneC.OnBoarding.DC.BGVDC.SaveComponent objSaveComponent) {
            return base.Channel.SaveVerificationData(objSaveComponent);
        }
        
        public OneC.OnBoarding.DC.BGVDC.Autocomplete AutoSearch(OneC.OnBoarding.DC.BGVDC.Autocomplete objAutocomplete) {
            return base.Channel.AutoSearch(objAutocomplete);
        }
        
        public OneC.OnBoarding.DC.BGVDC.Validation ValidateComponentData(OneC.OnBoarding.DC.BGVDC.Validation objValidation) {
            return base.Channel.ValidateComponentData(objValidation);
        }
        
        public string PersonalData(OneC.OnBoarding.DC.BGVDC.CandidateInformationDC objCandidateInformationDC) {
            return base.Channel.PersonalData(objCandidateInformationDC);
        }
        
        public int SavePersonalData(OneC.OnBoarding.DC.BGVDC.CandidateInformationDC objCandidateInformationDC) {
            return base.Channel.SavePersonalData(objCandidateInformationDC);
        }
        
        public OneC.OnBoarding.DC.BGVDC.ValidatePersonalData ValidatePersonalInfo(OneC.OnBoarding.DC.BGVDC.ValidatePersonalData objValidation) {
            return base.Channel.ValidatePersonalInfo(objValidation);
        }
        
        public string GetPagePathForRole(OneC.OnBoarding.DC.BGVDC.PageNavigationDC objPageNavigationDC) {
            return base.Channel.GetPagePathForRole(objPageNavigationDC);
        }
        
        public string[] GetPageNotifications(OneC.OnBoarding.DC.BGVDC.PageNotifications objPageNotifications) {
            return base.Channel.GetPageNotifications(objPageNotifications);
        }
        
        public string GetPageComparisionData(OneC.OnBoarding.DC.BGVDC.CompareDC objCompareDC) {
            return base.Channel.GetPageComparisionData(objCompareDC);
        }
    }
}
