//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneC.OnBoarding.WebApp.Service.GetFile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stellent.com/GetFile/", ConfigurationName="Service.GetFile.GetFileSoap")]
    public interface GetFileSoap {
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/GetFile/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDResponse GetFileByID(OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDRequest request);
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/GetFile/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameResponse GetFileByName(OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/GetFile/")]
    public partial class IdcProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/GetFile/")]
    public partial class GetFileByNameResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FileInfo[] fileInfoField;
        
        private IdcFile downloadFileField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FileInfo", Order=0)]
        public FileInfo[] FileInfo {
            get {
                return this.fileInfoField;
            }
            set {
                this.fileInfoField = value;
                this.RaisePropertyChanged("FileInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdcFile downloadFile {
            get {
                return this.downloadFileField;
            }
            set {
                this.downloadFileField = value;
                this.RaisePropertyChanged("downloadFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/GetFile/")]
    public partial class FileInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dDocNameField;
        
        private string dDocTitleField;
        
        private string dDocTypeField;
        
        private string dDocAuthorField;
        
        private string dSecurityGroupField;
        
        private string dDocAccountField;
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private int dRevClassIDField;
        
        private bool dRevClassIDFieldSpecified;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        private string dRevLabelField;
        
        private bool dIsCheckedOutField;
        
        private bool dIsCheckedOutFieldSpecified;
        
        private string dCheckoutUserField;
        
        private string dCreateDateField;
        
        private string dInDateField;
        
        private string dOutDateField;
        
        private string dStatusField;
        
        private string dReleaseStateField;
        
        private string dFlag1Field;
        
        private string dWebExtensionField;
        
        private string dProcessingStateField;
        
        private string dMessageField;
        
        private string dReleaseDateField;
        
        private string dRendition1Field;
        
        private string dRendition2Field;
        
        private string dIndexerStateField;
        
        private string dPublishTypeField;
        
        private string dPublishStateField;
        
        private int dDocIDField;
        
        private bool dDocIDFieldSpecified;
        
        private bool dIsPrimaryField;
        
        private bool dIsPrimaryFieldSpecified;
        
        private bool dIsWebFormatField;
        
        private bool dIsWebFormatFieldSpecified;
        
        private string dLocationField;
        
        private string dOriginalNameField;
        
        private string dFormatField;
        
        private string dExtensionField;
        
        private int dFileSizeField;
        
        private bool dFileSizeFieldSpecified;
        
        private IdcProperty[] customDocMetaDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dDocName {
            get {
                return this.dDocNameField;
            }
            set {
                this.dDocNameField = value;
                this.RaisePropertyChanged("dDocName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dDocTitle {
            get {
                return this.dDocTitleField;
            }
            set {
                this.dDocTitleField = value;
                this.RaisePropertyChanged("dDocTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dDocType {
            get {
                return this.dDocTypeField;
            }
            set {
                this.dDocTypeField = value;
                this.RaisePropertyChanged("dDocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dDocAuthor {
            get {
                return this.dDocAuthorField;
            }
            set {
                this.dDocAuthorField = value;
                this.RaisePropertyChanged("dDocAuthor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string dSecurityGroup {
            get {
                return this.dSecurityGroupField;
            }
            set {
                this.dSecurityGroupField = value;
                this.RaisePropertyChanged("dSecurityGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dDocAccount {
            get {
                return this.dDocAccountField;
            }
            set {
                this.dDocAccountField = value;
                this.RaisePropertyChanged("dDocAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int dID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("dID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified {
            get {
                return this.dIDFieldSpecified;
            }
            set {
                this.dIDFieldSpecified = value;
                this.RaisePropertyChanged("dIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int dRevClassID {
            get {
                return this.dRevClassIDField;
            }
            set {
                this.dRevClassIDField = value;
                this.RaisePropertyChanged("dRevClassID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified {
            get {
                return this.dRevClassIDFieldSpecified;
            }
            set {
                this.dRevClassIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevClassIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int dRevisionID {
            get {
                return this.dRevisionIDField;
            }
            set {
                this.dRevisionIDField = value;
                this.RaisePropertyChanged("dRevisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified {
            get {
                return this.dRevisionIDFieldSpecified;
            }
            set {
                this.dRevisionIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevisionIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dRevLabel {
            get {
                return this.dRevLabelField;
            }
            set {
                this.dRevLabelField = value;
                this.RaisePropertyChanged("dRevLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool dIsCheckedOut {
            get {
                return this.dIsCheckedOutField;
            }
            set {
                this.dIsCheckedOutField = value;
                this.RaisePropertyChanged("dIsCheckedOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsCheckedOutSpecified {
            get {
                return this.dIsCheckedOutFieldSpecified;
            }
            set {
                this.dIsCheckedOutFieldSpecified = value;
                this.RaisePropertyChanged("dIsCheckedOutSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dCheckoutUser {
            get {
                return this.dCheckoutUserField;
            }
            set {
                this.dCheckoutUserField = value;
                this.RaisePropertyChanged("dCheckoutUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string dCreateDate {
            get {
                return this.dCreateDateField;
            }
            set {
                this.dCreateDateField = value;
                this.RaisePropertyChanged("dCreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string dInDate {
            get {
                return this.dInDateField;
            }
            set {
                this.dInDateField = value;
                this.RaisePropertyChanged("dInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string dOutDate {
            get {
                return this.dOutDateField;
            }
            set {
                this.dOutDateField = value;
                this.RaisePropertyChanged("dOutDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string dStatus {
            get {
                return this.dStatusField;
            }
            set {
                this.dStatusField = value;
                this.RaisePropertyChanged("dStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string dReleaseState {
            get {
                return this.dReleaseStateField;
            }
            set {
                this.dReleaseStateField = value;
                this.RaisePropertyChanged("dReleaseState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string dFlag1 {
            get {
                return this.dFlag1Field;
            }
            set {
                this.dFlag1Field = value;
                this.RaisePropertyChanged("dFlag1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string dWebExtension {
            get {
                return this.dWebExtensionField;
            }
            set {
                this.dWebExtensionField = value;
                this.RaisePropertyChanged("dWebExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string dProcessingState {
            get {
                return this.dProcessingStateField;
            }
            set {
                this.dProcessingStateField = value;
                this.RaisePropertyChanged("dProcessingState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string dMessage {
            get {
                return this.dMessageField;
            }
            set {
                this.dMessageField = value;
                this.RaisePropertyChanged("dMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string dReleaseDate {
            get {
                return this.dReleaseDateField;
            }
            set {
                this.dReleaseDateField = value;
                this.RaisePropertyChanged("dReleaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string dRendition1 {
            get {
                return this.dRendition1Field;
            }
            set {
                this.dRendition1Field = value;
                this.RaisePropertyChanged("dRendition1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string dRendition2 {
            get {
                return this.dRendition2Field;
            }
            set {
                this.dRendition2Field = value;
                this.RaisePropertyChanged("dRendition2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string dIndexerState {
            get {
                return this.dIndexerStateField;
            }
            set {
                this.dIndexerStateField = value;
                this.RaisePropertyChanged("dIndexerState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string dPublishType {
            get {
                return this.dPublishTypeField;
            }
            set {
                this.dPublishTypeField = value;
                this.RaisePropertyChanged("dPublishType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string dPublishState {
            get {
                return this.dPublishStateField;
            }
            set {
                this.dPublishStateField = value;
                this.RaisePropertyChanged("dPublishState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int dDocID {
            get {
                return this.dDocIDField;
            }
            set {
                this.dDocIDField = value;
                this.RaisePropertyChanged("dDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dDocIDSpecified {
            get {
                return this.dDocIDFieldSpecified;
            }
            set {
                this.dDocIDFieldSpecified = value;
                this.RaisePropertyChanged("dDocIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool dIsPrimary {
            get {
                return this.dIsPrimaryField;
            }
            set {
                this.dIsPrimaryField = value;
                this.RaisePropertyChanged("dIsPrimary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsPrimarySpecified {
            get {
                return this.dIsPrimaryFieldSpecified;
            }
            set {
                this.dIsPrimaryFieldSpecified = value;
                this.RaisePropertyChanged("dIsPrimarySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public bool dIsWebFormat {
            get {
                return this.dIsWebFormatField;
            }
            set {
                this.dIsWebFormatField = value;
                this.RaisePropertyChanged("dIsWebFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsWebFormatSpecified {
            get {
                return this.dIsWebFormatFieldSpecified;
            }
            set {
                this.dIsWebFormatFieldSpecified = value;
                this.RaisePropertyChanged("dIsWebFormatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string dLocation {
            get {
                return this.dLocationField;
            }
            set {
                this.dLocationField = value;
                this.RaisePropertyChanged("dLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string dOriginalName {
            get {
                return this.dOriginalNameField;
            }
            set {
                this.dOriginalNameField = value;
                this.RaisePropertyChanged("dOriginalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string dFormat {
            get {
                return this.dFormatField;
            }
            set {
                this.dFormatField = value;
                this.RaisePropertyChanged("dFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string dExtension {
            get {
                return this.dExtensionField;
            }
            set {
                this.dExtensionField = value;
                this.RaisePropertyChanged("dExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public int dFileSize {
            get {
                return this.dFileSizeField;
            }
            set {
                this.dFileSizeField = value;
                this.RaisePropertyChanged("dFileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dFileSizeSpecified {
            get {
                return this.dFileSizeFieldSpecified;
            }
            set {
                this.dFileSizeFieldSpecified = value;
                this.RaisePropertyChanged("dFileSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=35)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public IdcProperty[] CustomDocMetaData {
            get {
                return this.customDocMetaDataField;
            }
            set {
                this.customDocMetaDataField = value;
                this.RaisePropertyChanged("CustomDocMetaData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/GetFile/")]
    public partial class IdcFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/GetFile/")]
    public partial class StatusInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
                this.RaisePropertyChanged("statusCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/GetFile/")]
    public partial class GetFileByIDResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FileInfo[] fileInfoField;
        
        private IdcFile downloadFileField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FileInfo", Order=0)]
        public FileInfo[] FileInfo {
            get {
                return this.fileInfoField;
            }
            set {
                this.fileInfoField = value;
                this.RaisePropertyChanged("FileInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdcFile downloadFile {
            get {
                return this.downloadFileField;
            }
            set {
                this.downloadFileField = value;
                this.RaisePropertyChanged("downloadFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByID", WrapperNamespace="http://www.stellent.com/GetFile/", IsWrapped=true)]
    public partial class GetFileByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=1)]
        public string rendition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public IdcProperty[] extraProps;
        
        public GetFileByIDRequest() {
        }
        
        public GetFileByIDRequest(int dID, string rendition, IdcProperty[] extraProps) {
            this.dID = dID;
            this.rendition = rendition;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByIDResponse", WrapperNamespace="http://www.stellent.com/GetFile/", IsWrapped=true)]
    public partial class GetFileByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=0)]
        public OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDResult GetFileByIDResult;
        
        public GetFileByIDResponse() {
        }
        
        public GetFileByIDResponse(OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDResult GetFileByIDResult) {
            this.GetFileByIDResult = GetFileByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByName", WrapperNamespace="http://www.stellent.com/GetFile/", IsWrapped=true)]
    public partial class GetFileByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=1)]
        public string revisionSelectionMethod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=2)]
        public string rendition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public IdcProperty[] extraProps;
        
        public GetFileByNameRequest() {
        }
        
        public GetFileByNameRequest(string dDocName, string revisionSelectionMethod, string rendition, IdcProperty[] extraProps) {
            this.dDocName = dDocName;
            this.revisionSelectionMethod = revisionSelectionMethod;
            this.rendition = rendition;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByNameResponse", WrapperNamespace="http://www.stellent.com/GetFile/", IsWrapped=true)]
    public partial class GetFileByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/GetFile/", Order=0)]
        public OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameResult GetFileByNameResult;
        
        public GetFileByNameResponse() {
        }
        
        public GetFileByNameResponse(OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameResult GetFileByNameResult) {
            this.GetFileByNameResult = GetFileByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetFileSoapChannel : OneC.OnBoarding.WebApp.Service.GetFile.GetFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFileSoapClient : System.ServiceModel.ClientBase<OneC.OnBoarding.WebApp.Service.GetFile.GetFileSoap>, OneC.OnBoarding.WebApp.Service.GetFile.GetFileSoap {
        
        public GetFileSoapClient() {
        }
        
        public GetFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDResponse OneC.OnBoarding.WebApp.Service.GetFile.GetFileSoap.GetFileByID(OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDRequest request) {
            return base.Channel.GetFileByID(request);
        }
        
        public OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDResult GetFileByID(int dID, string rendition, IdcProperty[] extraProps) {
            OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDRequest inValue = new OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDRequest();
            inValue.dID = dID;
            inValue.rendition = rendition;
            inValue.extraProps = extraProps;
            OneC.OnBoarding.WebApp.Service.GetFile.GetFileByIDResponse retVal = ((OneC.OnBoarding.WebApp.Service.GetFile.GetFileSoap)(this)).GetFileByID(inValue);
            return retVal.GetFileByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameResponse OneC.OnBoarding.WebApp.Service.GetFile.GetFileSoap.GetFileByName(OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameRequest request) {
            return base.Channel.GetFileByName(request);
        }
        
        public OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameResult GetFileByName(string dDocName, string revisionSelectionMethod, string rendition, IdcProperty[] extraProps) {
            OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameRequest inValue = new OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameRequest();
            inValue.dDocName = dDocName;
            inValue.revisionSelectionMethod = revisionSelectionMethod;
            inValue.rendition = rendition;
            inValue.extraProps = extraProps;
            OneC.OnBoarding.WebApp.Service.GetFile.GetFileByNameResponse retVal = ((OneC.OnBoarding.WebApp.Service.GetFile.GetFileSoap)(this)).GetFileByName(inValue);
            return retVal.GetFileByNameResult;
        }
    }
}
