//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneC.OnBoarding.WebApp.Service.CandidateServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FileDetailList", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/CandidateDC/", ItemName="FileDetail")]
    [System.SerializableAttribute()]
    public class FileDetailList : System.Collections.Generic.List<OneC.OnBoarding.DC.CandidateDC.FileDetail> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
        "racts/", ConfigurationName="Service.CandidateServices.ICandidateServices")]
    public interface ICandidateServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateELMStatus", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateELMStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateELMStatusOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        void UpdateELMStatus(OneC.OnBoarding.DC.CandidateDC.ELMDC[] elmLIST);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateId", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateIdOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.CandidateDetail[] FetchCandidateId(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchStateTaxFormList", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchStateTaxFormListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchStateTaxFormListOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.CandidateDetail[] FetchStateTaxFormList(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveSurveyData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveSurveyDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveSurveyDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SaveSurveyData([System.ServiceModel.MessageParameterAttribute(Name="saveSurveydata")] OneC.OnBoarding.DC.CandidateDC.SaveTaskDC saveSurveydata1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchFileUploadData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchFileUploadDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchFileUploadDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.FileUploadDC FetchFileUploadData(OneC.OnBoarding.DC.CandidateDC.FileUploadDC uploadData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateStatus", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateStatusOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UpdateStatus(OneC.OnBoarding.DC.CandidateDC.VirtualDocumentDC objDocumentDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateCisContent", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateCisContentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateCisContentOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.SaveCisDC ValidateCisContent(OneC.OnBoarding.DC.CandidateDC.SaveCisDC objCis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveCandidateComponentData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveCandidateComponentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveCandidateComponentDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.SaveCisDC SaveCandidateComponentData(OneC.OnBoarding.DC.CandidateDC.SaveCisDC objCandidateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateComponentData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateComponentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateComponentDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.SaveCisDC ValidateComponentData(OneC.OnBoarding.DC.CandidateDC.SaveCisDC objComponentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveCisData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveCisDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveCisDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SaveCisData([System.ServiceModel.MessageParameterAttribute(Name="saveCisdata")] OneC.OnBoarding.DC.CandidateDC.SaveCisDC saveCisdata1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetNHDashboardBgvStatus", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetNHDashboardBgvStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetNHDashboardBgvStatusOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.BgvNHDashboardData GetNHDashboardBgvStatus(OneC.OnBoarding.DC.CandidateDC.BgvNHDashboardData objNHDashboardData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveBpNoGo", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveBpNoGoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveBpNoGoOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SaveBpNoGo([System.ServiceModel.MessageParameterAttribute(Name="saveBpNoGo")] OneC.OnBoarding.DC.CandidateDC.SaveCisDC saveBpNoGo1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/PendingBackPaperCount", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/PendingBackPaperCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/PendingBackPaperCountOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int PendingBackPaperCount(OneC.OnBoarding.DC.CandidateDC.SaveCisDC saveBpNoGo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/saveFeedback", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/saveFeedbackResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/saveFeedbackOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int saveFeedback([System.ServiceModel.MessageParameterAttribute(Name="saveFeedback")] OneC.OnBoarding.DC.CandidateDC.SaveRLAFeedbackDC saveFeedback1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateTracking", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateTrackingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateTrackingOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.CandidateDetail[] FetchCandidateTracking(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTaskList", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTaskListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTaskListOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.TaskDetail[] FetchTaskList(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateType", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateTypeOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.CandidateTypeDC[] FetchCandidateType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateHireType", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateHireTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchCandidateHireTypeOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.CandidateTypeDC[] FetchCandidateHireType(OneC.OnBoarding.DC.CandidateDC.CandidateTypeDC parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchMasterData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchMasterDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchMasterDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.MasterListSource FetchMasterData(OneC.OnBoarding.DC.CandidateDC.MasterList parentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetPrefillValues", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetPrefillValuesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetPrefillValuesOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.SaveTaskDC GetPrefillValues(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC prefillvalues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveTaskData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveTaskDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveTaskDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int SaveTaskData([System.ServiceModel.MessageParameterAttribute(Name="saveTaskdata")] OneC.OnBoarding.DC.CandidateDC.SaveTaskDC saveTaskdata1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateAuthenticationKey", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateAuthenticationKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateAuthenticationKeyOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int ValidateAuthenticationKey(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC getSignKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateTaskContent", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateTaskContentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ValidateTaskContentOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.SaveTaskDC ValidateTaskContent(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetHtmlContentToGeneratePDF", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetHtmlContentToGeneratePDFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetHtmlContentToGeneratePDFOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string GetHtmlContentToGeneratePDF(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC getParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetGeographyMaster", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetGeographyMasterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetGeographyMasterOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.UtilityDC.CountryListSource GetGeographyMaster(OneC.OnBoarding.DC.UtilityDC.Country country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ResetAuthenticationKey", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ResetAuthenticationKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/ResetAuthenticationKeyOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        void ResetAuthenticationKey(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC resetKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveMeetingID", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveMeetingIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SaveMeetingIDOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        void SaveMeetingID(OneC.OnBoarding.DC.CandidateDC.SaveMeetingID meetingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchFaq", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchFaqResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchFaqOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        string FetchFaq(OneC.OnBoarding.DC.CandidateDC.FaqSearch faqSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingMaster", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingMasterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingMasterOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTrainingMaster(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTraining);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingStatus", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingStatusOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTrainingStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTraningData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTraningDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTraningDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTraningData(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objDc, OneC.OnBoarding.DC.DashBoardDC.TotalCountDC totalCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateTrainingDate", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateTrainingDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateTrainingDateOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UpdateTrainingDate(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTrainingList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDrillDownData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDrillDownDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDrillDownDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC[] FetchTrainingDrillDownData(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC objTrainingDrillDown);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDates", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDatesOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC[] FetchTrainingDates(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDetails", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/FetchTrainingDetailsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTrainingDetails(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTrainingDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/PopulateCandidateTrainingDetails", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/PopulateCandidateTrainingDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/PopulateCandidateTrainingDetailsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] PopulateCandidateTrainingDetails(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SendInductionDiaryInvites", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SendInductionDiaryInvitesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/SendInductionDiaryInvitesOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] SendInductionDiaryInvites(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/RegisterCancelTrainingDetails", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/RegisterCancelTrainingDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/RegisterCancelTrainingDetailsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] RegisterCancelTrainingDetails(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateCandidateTrainingDate", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateCandidateTrainingDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateCandidateTrainingDateOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UpdateCandidateTrainingDate(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC candidateDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetEmployersDetails", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetEmployersDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetEmployersDetailsOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.SaveTaskDC GetEmployersDetails(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC getEmployerdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateNHOTrainingData", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateNHOTrainingDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/UpdateNHOTrainingDataOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        int UpdateNHOTrainingData(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTrainingList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetMedicalTopupCover", ReplyAction="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetMedicalTopupCoverResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneC.OnBoarding.DC.UtilityDC.OBFaultContractFC), Action="http://onecognizant.cognizant.com/OnBoardingService/CandidateServices/ServiceCont" +
            "racts/ICandidateServices/GetMedicalTopupCoverOBFaultContractFCFault", Name="OBFaultContractFC", Namespace="http://onecognizant.cognizant.com/OnBoardingService/DataContracts/UtilityDC/")]
        OneC.OnBoarding.DC.CandidateDC.MasterListSource GetMedicalTopupCover(OneC.OnBoarding.DC.CandidateDC.MasterList getcandidateID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICandidateServicesChannel : OneC.OnBoarding.WebApp.Service.CandidateServices.ICandidateServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CandidateServicesClient : System.ServiceModel.ClientBase<OneC.OnBoarding.WebApp.Service.CandidateServices.ICandidateServices>, OneC.OnBoarding.WebApp.Service.CandidateServices.ICandidateServices {
        
        public CandidateServicesClient() {
        }
        
        public CandidateServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CandidateServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandidateServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandidateServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateELMStatus(OneC.OnBoarding.DC.CandidateDC.ELMDC[] elmLIST) {
            base.Channel.UpdateELMStatus(elmLIST);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.CandidateDetail[] FetchCandidateId(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail) {
            return base.Channel.FetchCandidateId(candidateDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.CandidateDetail[] FetchStateTaxFormList(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail) {
            return base.Channel.FetchStateTaxFormList(candidateDetail);
        }
        
        public int SaveSurveyData(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC saveSurveydata1) {
            return base.Channel.SaveSurveyData(saveSurveydata1);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.FileUploadDC FetchFileUploadData(OneC.OnBoarding.DC.CandidateDC.FileUploadDC uploadData) {
            return base.Channel.FetchFileUploadData(uploadData);
        }
        
        public int UpdateStatus(OneC.OnBoarding.DC.CandidateDC.VirtualDocumentDC objDocumentDetail) {
            return base.Channel.UpdateStatus(objDocumentDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.SaveCisDC ValidateCisContent(OneC.OnBoarding.DC.CandidateDC.SaveCisDC objCis) {
            return base.Channel.ValidateCisContent(objCis);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.SaveCisDC SaveCandidateComponentData(OneC.OnBoarding.DC.CandidateDC.SaveCisDC objCandidateData) {
            return base.Channel.SaveCandidateComponentData(objCandidateData);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.SaveCisDC ValidateComponentData(OneC.OnBoarding.DC.CandidateDC.SaveCisDC objComponentData) {
            return base.Channel.ValidateComponentData(objComponentData);
        }
        
        public int SaveCisData(OneC.OnBoarding.DC.CandidateDC.SaveCisDC saveCisdata1) {
            return base.Channel.SaveCisData(saveCisdata1);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.BgvNHDashboardData GetNHDashboardBgvStatus(OneC.OnBoarding.DC.CandidateDC.BgvNHDashboardData objNHDashboardData) {
            return base.Channel.GetNHDashboardBgvStatus(objNHDashboardData);
        }
        
        public int SaveBpNoGo(OneC.OnBoarding.DC.CandidateDC.SaveCisDC saveBpNoGo1) {
            return base.Channel.SaveBpNoGo(saveBpNoGo1);
        }
        
        public int PendingBackPaperCount(OneC.OnBoarding.DC.CandidateDC.SaveCisDC saveBpNoGo) {
            return base.Channel.PendingBackPaperCount(saveBpNoGo);
        }
        
        public int saveFeedback(OneC.OnBoarding.DC.CandidateDC.SaveRLAFeedbackDC saveFeedback1) {
            return base.Channel.saveFeedback(saveFeedback1);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.CandidateDetail[] FetchCandidateTracking(OneC.OnBoarding.DC.UtilityDC.SessionDetails sessionDetail) {
            return base.Channel.FetchCandidateTracking(sessionDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.TaskDetail[] FetchTaskList(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail) {
            return base.Channel.FetchTaskList(candidateDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.CandidateTypeDC[] FetchCandidateType() {
            return base.Channel.FetchCandidateType();
        }
        
        public OneC.OnBoarding.DC.CandidateDC.CandidateTypeDC[] FetchCandidateHireType(OneC.OnBoarding.DC.CandidateDC.CandidateTypeDC parentId) {
            return base.Channel.FetchCandidateHireType(parentId);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.MasterListSource FetchMasterData(OneC.OnBoarding.DC.CandidateDC.MasterList parentCode) {
            return base.Channel.FetchMasterData(parentCode);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.SaveTaskDC GetPrefillValues(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC prefillvalues) {
            return base.Channel.GetPrefillValues(prefillvalues);
        }
        
        public int SaveTaskData(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC saveTaskdata1) {
            return base.Channel.SaveTaskData(saveTaskdata1);
        }
        
        public int ValidateAuthenticationKey(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC getSignKey) {
            return base.Channel.ValidateAuthenticationKey(getSignKey);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.SaveTaskDC ValidateTaskContent(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC param) {
            return base.Channel.ValidateTaskContent(param);
        }
        
        public string GetHtmlContentToGeneratePDF(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC getParams) {
            return base.Channel.GetHtmlContentToGeneratePDF(getParams);
        }
        
        public OneC.OnBoarding.DC.UtilityDC.CountryListSource GetGeographyMaster(OneC.OnBoarding.DC.UtilityDC.Country country) {
            return base.Channel.GetGeographyMaster(country);
        }
        
        public void ResetAuthenticationKey(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC resetKey) {
            base.Channel.ResetAuthenticationKey(resetKey);
        }
        
        public void SaveMeetingID(OneC.OnBoarding.DC.CandidateDC.SaveMeetingID meetingDetail) {
            base.Channel.SaveMeetingID(meetingDetail);
        }
        
        public string FetchFaq(OneC.OnBoarding.DC.CandidateDC.FaqSearch faqSearch) {
            return base.Channel.FetchFaq(faqSearch);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTrainingMaster(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTraining) {
            return base.Channel.FetchTrainingMaster(objTraining);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTrainingStatus() {
            return base.Channel.FetchTrainingStatus();
        }
        
        public OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTraningData(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objDc, OneC.OnBoarding.DC.DashBoardDC.TotalCountDC totalCount) {
            return base.Channel.FetchTraningData(objDc, totalCount);
        }
        
        public int UpdateTrainingDate(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTrainingList) {
            return base.Channel.UpdateTrainingDate(objTrainingList);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC[] FetchTrainingDrillDownData(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC objTrainingDrillDown) {
            return base.Channel.FetchTrainingDrillDownData(objTrainingDrillDown);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC[] FetchTrainingDates(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail) {
            return base.Channel.FetchTrainingDates(candidateDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] FetchTrainingDetails(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTrainingDC) {
            return base.Channel.FetchTrainingDetails(objTrainingDC);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] PopulateCandidateTrainingDetails(OneC.OnBoarding.DC.CandidateDC.CandidateDetail candidateDetail) {
            return base.Channel.PopulateCandidateTrainingDetails(candidateDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] SendInductionDiaryInvites(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC candidateDetail) {
            return base.Channel.SendInductionDiaryInvites(candidateDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC[] RegisterCancelTrainingDetails(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC candidateDetail) {
            return base.Channel.RegisterCancelTrainingDetails(candidateDetail);
        }
        
        public int UpdateCandidateTrainingDate(OneC.OnBoarding.DC.CandidateDC.CandidateTrainingDC candidateDetail) {
            return base.Channel.UpdateCandidateTrainingDate(candidateDetail);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.SaveTaskDC GetEmployersDetails(OneC.OnBoarding.DC.CandidateDC.SaveTaskDC getEmployerdata) {
            return base.Channel.GetEmployersDetails(getEmployerdata);
        }
        
        public int UpdateNHOTrainingData(OneC.OnBoarding.DC.CandidateDC.NewHireTrainingDC objTrainingList) {
            return base.Channel.UpdateNHOTrainingData(objTrainingList);
        }
        
        public OneC.OnBoarding.DC.CandidateDC.MasterListSource GetMedicalTopupCover(OneC.OnBoarding.DC.CandidateDC.MasterList getcandidateID) {
            return base.Channel.GetMedicalTopupCover(getcandidateID);
        }
    }
}
