//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneC.OnBoarding.WebApp.IDMSvcRefFromIDM {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewHireDetails", Namespace="http://schemas.datacontract.org/2004/07/Cognizant.Eums.Business.Interfaces")]
    [System.SerializableAttribute()]
    public partial class NewHireDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTUALSTARTDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AUTHENTICATIONKEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CANDIDATEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANYNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COUNTRYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESAHIRINGMANAGERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIRSTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HIRETYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LASTDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LASTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MIDDLENAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROJECTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROJECTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RECRUITEREMAILADDRESSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTUALSTARTDATE {
            get {
                return this.ACTUALSTARTDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTUALSTARTDATEField, value) != true)) {
                    this.ACTUALSTARTDATEField = value;
                    this.RaisePropertyChanged("ACTUALSTARTDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AUTHENTICATIONKEY {
            get {
                return this.AUTHENTICATIONKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.AUTHENTICATIONKEYField, value) != true)) {
                    this.AUTHENTICATIONKEYField = value;
                    this.RaisePropertyChanged("AUTHENTICATIONKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CANDIDATEID {
            get {
                return this.CANDIDATEIDField;
            }
            set {
                if ((this.CANDIDATEIDField.Equals(value) != true)) {
                    this.CANDIDATEIDField = value;
                    this.RaisePropertyChanged("CANDIDATEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANYNAME {
            get {
                return this.COMPANYNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANYNAMEField, value) != true)) {
                    this.COMPANYNAMEField = value;
                    this.RaisePropertyChanged("COMPANYNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COUNTRY {
            get {
                return this.COUNTRYField;
            }
            set {
                if ((object.ReferenceEquals(this.COUNTRYField, value) != true)) {
                    this.COUNTRYField = value;
                    this.RaisePropertyChanged("COUNTRY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAILADDRESS {
            get {
                return this.EMAILADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILADDRESSField, value) != true)) {
                    this.EMAILADDRESSField = value;
                    this.RaisePropertyChanged("EMAILADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESAHIRINGMANAGERID {
            get {
                return this.ESAHIRINGMANAGERIDField;
            }
            set {
                if ((this.ESAHIRINGMANAGERIDField.Equals(value) != true)) {
                    this.ESAHIRINGMANAGERIDField = value;
                    this.RaisePropertyChanged("ESAHIRINGMANAGERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIRSTNAME {
            get {
                return this.FIRSTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIRSTNAMEField, value) != true)) {
                    this.FIRSTNAMEField = value;
                    this.RaisePropertyChanged("FIRSTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HIRETYPE {
            get {
                return this.HIRETYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.HIRETYPEField, value) != true)) {
                    this.HIRETYPEField = value;
                    this.RaisePropertyChanged("HIRETYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LASTDATE {
            get {
                return this.LASTDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.LASTDATEField, value) != true)) {
                    this.LASTDATEField = value;
                    this.RaisePropertyChanged("LASTDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LASTNAME {
            get {
                return this.LASTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.LASTNAMEField, value) != true)) {
                    this.LASTNAMEField = value;
                    this.RaisePropertyChanged("LASTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MIDDLENAME {
            get {
                return this.MIDDLENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.MIDDLENAMEField, value) != true)) {
                    this.MIDDLENAMEField = value;
                    this.RaisePropertyChanged("MIDDLENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROJECTID {
            get {
                return this.PROJECTIDField;
            }
            set {
                if ((this.PROJECTIDField.Equals(value) != true)) {
                    this.PROJECTIDField = value;
                    this.RaisePropertyChanged("PROJECTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROJECTNAME {
            get {
                return this.PROJECTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PROJECTNAMEField, value) != true)) {
                    this.PROJECTNAMEField = value;
                    this.RaisePropertyChanged("PROJECTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RECRUITEREMAILADDRESS {
            get {
                return this.RECRUITEREMAILADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.RECRUITEREMAILADDRESSField, value) != true)) {
                    this.RECRUITEREMAILADDRESSField = value;
                    this.RaisePropertyChanged("RECRUITEREMAILADDRESS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TerminationFeedDetails", Namespace="http://schemas.datacontract.org/2004/07/Cognizant.Eums.Business.Interfaces")]
    [System.SerializableAttribute()]
    public partial class TerminationFeedDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CANDIDATEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LASTDATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CANDIDATEID {
            get {
                return this.CANDIDATEIDField;
            }
            set {
                if ((this.CANDIDATEIDField.Equals(value) != true)) {
                    this.CANDIDATEIDField = value;
                    this.RaisePropertyChanged("CANDIDATEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LASTDATE {
            get {
                return this.LASTDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.LASTDATEField, value) != true)) {
                    this.LASTDATEField = value;
                    this.RaisePropertyChanged("LASTDATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDMSvcRefFromIDM.IService_EUMS")]
    public interface IService_EUMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/SaveNewHireDetails", ReplyAction="http://tempuri.org/IService_EUMS/SaveNewHireDetailsResponse")]
        string SaveNewHireDetails(out System.Collections.Generic.Dictionary<string, string> failedUsersDetails, OneC.OnBoarding.WebApp.IDMSvcRefFromIDM.NewHireDetails[] newHireList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/UpdateUserTerminationFeed", ReplyAction="http://tempuri.org/IService_EUMS/UpdateUserTerminationFeedResponse")]
        string UpdateUserTerminationFeed(out System.Collections.Generic.Dictionary<string, string> failedUsersDetails, OneC.OnBoarding.WebApp.IDMSvcRefFromIDM.TerminationFeedDetails[] terminationFeedList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/ResendMailstoNewHire", ReplyAction="http://tempuri.org/IService_EUMS/ResendMailstoNewHireResponse")]
        string ResendMailstoNewHire(out string errorMessage, string userEmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/GetRegistrationStatus", ReplyAction="http://tempuri.org/IService_EUMS/GetRegistrationStatusResponse")]
        string GetRegistrationStatus(string UserEmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/UpdateRegistrationStatusFromTIM", ReplyAction="http://tempuri.org/IService_EUMS/UpdateRegistrationStatusFromTIMResponse")]
        bool UpdateRegistrationStatusFromTIM(string UserName, long RequestId, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/GetOneCommunicatorResponse", ReplyAction="http://tempuri.org/IService_EUMS/GetOneCommunicatorResponseResponse")]
        void GetOneCommunicatorResponse(string outputXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/UpdateAuthenticationKey", ReplyAction="http://tempuri.org/IService_EUMS/UpdateAuthenticationKeyResponse")]
        bool UpdateAuthenticationKey(out string errorMessage, string EmailAddress, string Authenticationkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_EUMS/NewHireLoginValidation", ReplyAction="http://tempuri.org/IService_EUMS/NewHireLoginValidationResponse")]
        bool NewHireLoginValidation(string emailAddress, string authenticationKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_EUMSChannel : OneC.OnBoarding.WebApp.IDMSvcRefFromIDM.IService_EUMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_EUMSClient : System.ServiceModel.ClientBase<OneC.OnBoarding.WebApp.IDMSvcRefFromIDM.IService_EUMS>, OneC.OnBoarding.WebApp.IDMSvcRefFromIDM.IService_EUMS {
        
        public Service_EUMSClient() {
        }
        
        public Service_EUMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_EUMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_EUMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_EUMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveNewHireDetails(out System.Collections.Generic.Dictionary<string, string> failedUsersDetails, OneC.OnBoarding.WebApp.IDMSvcRefFromIDM.NewHireDetails[] newHireList) {
            return base.Channel.SaveNewHireDetails(out failedUsersDetails, newHireList);
        }
        
        public string UpdateUserTerminationFeed(out System.Collections.Generic.Dictionary<string, string> failedUsersDetails, OneC.OnBoarding.WebApp.IDMSvcRefFromIDM.TerminationFeedDetails[] terminationFeedList) {
            return base.Channel.UpdateUserTerminationFeed(out failedUsersDetails, terminationFeedList);
        }
        
        public string ResendMailstoNewHire(out string errorMessage, string userEmailAddress) {
            return base.Channel.ResendMailstoNewHire(out errorMessage, userEmailAddress);
        }
        
        public string GetRegistrationStatus(string UserEmailAddress) {
            return base.Channel.GetRegistrationStatus(UserEmailAddress);
        }
        
        public bool UpdateRegistrationStatusFromTIM(string UserName, long RequestId, string Status) {
            return base.Channel.UpdateRegistrationStatusFromTIM(UserName, RequestId, Status);
        }
        
        public void GetOneCommunicatorResponse(string outputXml) {
            base.Channel.GetOneCommunicatorResponse(outputXml);
        }
        
        public bool UpdateAuthenticationKey(out string errorMessage, string EmailAddress, string Authenticationkey) {
            return base.Channel.UpdateAuthenticationKey(out errorMessage, EmailAddress, Authenticationkey);
        }
        
        public bool NewHireLoginValidation(string emailAddress, string authenticationKey) {
            return base.Channel.NewHireLoginValidation(emailAddress, authenticationKey);
        }
    }
}
